### ISSUE TITLE
프로젝트 초기 설정 및 구조화

### ISSUE THREAD

**Issue by HyunJaae** [HyunJaae/stockscope#1]
### Todo
- [x] 기본 프로젝트 생성
- [x] 패키지 구조 설정
- [x] 공통 설정 클래스 구성
- [x] 예외 처리 구조 구현

### Review
- [x] 성능 테스트
- [x] 테스트 커버리지
