### ISSUE TITLE
CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by HyunJaae** [HyunJaae/stockscope#3]
### Todo
- [x] GitHub Actions 설정
- [x] Docker 설정
- [x] AWS 배포 환경 구성

### Review
- [x] GitHub Action 테스트
- [x] Docker 실행 테스트
